# fly.toml app configuration file generated for portfoleo-old-frog-3382 on 2025-03-24T23:13:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfoleo-old-frog-3382'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
